blogapp/newsletters/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import InputRequired
from flask_wtf.file import FileField, FileAllowed, FileRequired


class NewsletterForm(FlaskForm):
    subject = StringField('Subject', validators=[InputRequired()])
    message = TextAreaField('Message', validators=[InputRequired()])
    newsletter_file = FileField("Newsletter", validators=[FileAllowed(['pdf']), FileRequired()])
    submit = SubmitField('Create')


class UpdateNewsletterForm(FlaskForm):
    subject = StringField('Subject', validators=[InputRequired()])
    message = TextAreaField('Message', validators=[InputRequired()])
    newsletter_file = FileField("Newsletter", validators=[FileAllowed(['pdf'])])
    submit = SubmitField('Update')

blogapp/posts/forms.py
from flask_wtf import FlaskForm
from flask_ckeditor import CKEditorField
from wtforms import StringField, SubmitField, SelectField, TextAreaField
from wtforms.validators import InputRequired, ValidationError
from flask_wtf.file import FileField, FileAllowed

CATEGORY_CHOICES = [
    'Please select a category',
    'Travel',
    'Technology',
    'Books',
    'Activities',
    'Work'
]


class PostForm(FlaskForm):
    title = StringField('Title', validators=[InputRequired()])
    subtitle = StringField('Subtitle', validators=[InputRequired()])
    category = SelectField('Category', choices=CATEGORY_CHOICES, validators=[InputRequired()])
    content = CKEditorField('Content', validators=[InputRequired()])
    post_pic = FileField("Post Picture", validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')

    def validate_category(self, category):
        if category.data == 'Please select a category':
            raise ValidationError('Please select a category')


class CommentForm(FlaskForm):
    content = TextAreaField('Write a comment', validators=[InputRequired()])
    submit = SubmitField('Post')

blogapp/main/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from blogapp import db
from blogapp.models import Post, User
from blogapp import mail
from blogapp.main.forms import SearchForm, ContactUsForm
from flask_mail import Message
categories = [
    'Travel',
    'Technology',
    'Books',
    'Activities',
    'Work'
]

archives = [
    "2024",
    "2023",
    "2022",
    "2021",
    "2020"
]

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = db.paginate(db.select(Post).order_by(Post.date_posted.desc()), page=page, per_page=3)
    return render_template("index.html", posts=posts)


@main.route('/about')
def about():
    return render_template("about.html", title="About")


@main.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactUsForm()
    if form.validate_on_submit():
        msg = Message(
            subject=f"Contact Us Query from: {form.name.data}, email: {form.email.data}",
            sender="kagandajohn762@gmail.com",
            recipients=["kagandajohn762@gmail.com"],
            body=form.message.data
        )
        mail.send(msg)
        flash("Your query has been received! We will respond as soon as we can.", "success")
        return redirect(url_for("main.home"))
    return render_template("contact.html", form=form, title="Contact")


@main.route('/search', methods=['GET', 'POST'])
def search():
    stmt = db.select(Post).order_by(Post.date_posted.desc())
    page = request.args.get('page', 1, type=int)
    param = request.args.get("param")
    username = request.args.get("username")

    search_value = request.form.get("search")
    if search_value:
        stmt = db.select(Post).where(Post.content.icontains(search_value)).order_by(Post.date_posted.desc())
    elif param in categories:
        stmt = db.select(Post).filter_by(category=param).order_by(Post.date_posted.desc())
    elif param in archives:
        stmt = db.select(Post).where(Post.date_posted.icontains(param)).order_by(Post.date_posted.desc())
    elif param:
        stmt = db.select(Post).where(Post.author_username == param).order_by(Post.date_posted.desc())

    posts = db.paginate(stmt, page=page, per_page=3)
    return render_template("search.html", param_value=param, search_value=search_value, posts=posts, title="Search")

blogapp/newsletters/routes.py
from flask import Blueprint, render_template, redirect, flash, request, url_for
from blogapp import db
from flask_login import login_required, current_user
from blogapp.models import Newsletter
from blogapp.newsletters.forms import NewsletterForm, UpdateNewsletterForm
from blogapp.newsletters.utils import (save_newsletter_file, admin_required, delete_newsletter_file,
                                       send_newsletter_email)
from datetime import datetime, timezone


newsletters = Blueprint('newsletters', __name__)


@newsletters.route('/newsletter/new', methods=['GET', 'POST'])
@admin_required
@login_required
def new_newsletter():
    form = NewsletterForm()
    if form.validate_on_submit():
        newsletter_fn = save_newsletter_file(form.newsletter_file.data)
        newsletter_new = Newsletter(
            subject=form.subject.data,
            message=form.message.data,
            author=current_user.username,
            date_created=datetime.now(timezone.utc),
            newsletter_file=newsletter_fn
        )
        db.session.add(newsletter_new)
        db.session.commit()
        flash("Your newsletter has been created!", "success")
        return redirect(url_for('newsletters.newsletter_home'))

    return render_template("create_edit_newsletter.html", form=form,
                           legend="New Newsletter", title="New Newsletter")


@newsletters.route('/newsletter/<int:newsletter_id>', methods=['GET', 'POST'])
@admin_required
@login_required
def newsletter(newsletter_id):
    newsletter = db.get_or_404(Newsletter, newsletter_id)
    return render_template("newsletter.html", legend="Newsletter",
                           newsletter=newsletter, title="Newsletter")


@newsletters.route('/newsletter/<int:newsletter_id>/update', methods=['GET', 'POST'])
@admin_required
@login_required
def update_newsletter(newsletter_id):
    newsletter = db.get_or_404(Newsletter, newsletter_id)
    form = UpdateNewsletterForm()
    if form.validate_on_submit():
        if form.newsletter_file.data:
            delete_newsletter_file(newsletter.newsletter_file)
            file_name = save_newsletter_file(form.newsletter_file.data)
            newsletter.newsletter_file = file_name
        newsletter.subject = form.subject.data
        newsletter.message = form.message.data
        db.session.commit()
        flash("Your newsletter has been updated!", "success")
        return redirect(url_for('newsletters.newsletter', newsletter_id=newsletter.id))
    elif request.method == 'GET':
        form.subject.data = newsletter.subject
        form.message.data = newsletter.message
    newsletter_fn = newsletter.newsletter_file

    return render_template("create_edit_newsletter.html", form=form, letter_id=newsletter.id,
                           newsletter_file=newsletter_fn, legend="Update Newsletter", title="Update Newsletter")


@newsletters.route('/newsletter/<int:newsletter_id>/delete', methods=['POST'])
@admin_required
@login_required
def delete_newsletter(newsletter_id):
    newsletter = db.get_or_404(Newsletter, newsletter_id)
    delete_newsletter_file(newsletter.newsletter_file)
    db.session.delete(newsletter)
    db.session.commit()
    flash("Your newsletter has been deleted!", "success")
    return redirect(url_for("newsletters.newsletter_home"))


@newsletters.route('/newsletter/<int:newsletter_id>/email', methods=['POST'])
@admin_required
@login_required
def email_newsletter(newsletter_id):
    newsletter = db.get_or_404(Newsletter, newsletter_id)
    email_sent = send_newsletter_email(newsletter)
    if email_sent:
        flash("Your newsletter has been emailed to all subscribers!", "success")
    else:
        flash("Your newsletter was not emailed. Please check the subscriber list!", "danger")
    return redirect(url_for("newsletters.newsletter_home"))


@newsletters.route('/newsletter', methods=['GET', 'POST'])
@admin_required
@login_required
def newsletter_home():
    page = request.args.get('page', 1, type=int)
    newsletters = db.paginate(db.select(Newsletter).order_by(Newsletter.date_created.desc()), page=page, per_page=12)
    return render_template("newsletter_list.html", newsletters=newsletters, title="newsletters Home")

blogapp/posts/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash, abort
from flask_login import login_required, current_user
from blogapp import db
from blogapp.models import Post, Comment, Reply
from blogapp.posts.forms import PostForm, CommentForm
from datetime import datetime, timezone
from blogapp.posts.utils import admin_required, sanitizer, save_picture, delete_picture

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@admin_required
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        clean_content = sanitizer.sanitize(form.content.data)
        post_new = Post(
            title=form.title.data,
            subtitle=form.subtitle.data,
            category=form.category.data,
            content=clean_content,
            author=current_user,
            author_username=current_user.username,
            date_posted=datetime.now(timezone.utc)
        )
        if form.post_pic.data:
            picture_name = save_picture(form.post_pic.data, "post")
            post_new.post_pic = picture_name
        db.session.add(post_new)
        db.session.commit()
        flash('Your post has been created!', "success")
        return redirect(url_for('main.home'))

    return render_template("create_edit_post.html", form=form, title="New Post", legend="New Post")


@posts.route('/post/<int:post_id>', methods=["GET", "POST"])
def show_post(post_id):
    post = db.get_or_404(Post, post_id)
    form = CommentForm()
    # The CommentForm is used for the reply form because their structure the same.
    reply_form = CommentForm()

    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('You must login or register to comment.', "danger")
            return redirect(url_for('users.login'))
        new_comment = Comment(
            content=form.content.data,
            comment_author=current_user,
            parent_post=post,
            date_posted=datetime.now(timezone.utc)
        )
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('posts.show_post', post_id=post.id))
    num_comments = len(post.comments)
    return render_template("post.html", post=post, form=form, reply_form=reply_form, num_comments=num_comments,
                           title="Post")


@posts.route('/reply/<int:comment_id>', methods=["POST"])
def new_reply(comment_id):
    if not current_user.is_authenticated:
        flash('You must login or register to reply.', "danger")
        return redirect(url_for('users.login'))
    comment = db.session.execute(db.select(Comment).where(Comment.id == comment_id)).scalar()
    # The CommentForm is used for the reply form because their structure the same.
    reply_form = CommentForm()
    # Note: In the post.html file, in the reply form the novalidate attribute has been removed to prevent
    # the user from submitting an empty reply.This is used
    # because the validation error won't be shown when the user
    # is redirected to the post.html file if validation fails.
    if reply_form.validate_on_submit():
        reply = Reply(
            content=reply_form.content.data,
            date_posted=datetime.now(timezone.utc),
            reply_author=current_user,
            comment_post=comment
        )
        db.session.add(reply)
        db.session.commit()
        return redirect(url_for('posts.show_post', post_id=comment.post_id))
    return redirect(url_for('posts.show_post', post_id=comment.post_id))


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@admin_required
@login_required
def update_post(post_id):
    post = db.get_or_404(Post, post_id)
    form = PostForm()
    if form.validate_on_submit():
        if form.post_pic.data:
            delete_picture(post.post_pic, "post")
            picture_name = save_picture(form.post_pic.data, "post")
            post.post_pic = picture_name
        post.title = form.title.data
        post.subtitle = form.subtitle.data
        post.category = form.category.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', "success")
        return redirect(url_for('posts.show_post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.subtitle.data = post.subtitle
        form.category.data = post.category
        form.content.data = post.content
    post_picture = url_for('static', filename=f'post_pics/{post.post_pic}')

    return render_template("create_edit_post.html", form=form, title="Update Post", image_file=post_picture,
                           legend="Update Post")


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@admin_required
@login_required
def delete_post(post_id):
    post = db.get_or_404(Post, post_id)
    delete_picture(post.post_pic, "post")
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', "success")
    return redirect(url_for('main.home'))

blogapp/templates/create_edit_newsletter.html
{% include "header.html" %}

<div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">

          <article class="card mb-4">
            <div class="card-body">
              <form action="{{ url_for('newsletters.new_newsletter') if legend == 'New Newsletter' else url_for('newsletters.update_newsletter', newsletter_id=letter_id) }}" method="post" enctype="multipart/form-data" novalidate>
                  {{ form.csrf_token }}
                  <legend class="border-bottom mb-4">{{ legend }}</legend>
                  <div class="form-group">
                      {{ form.subject.label(class_="form-label" ) }}
                      {% if form.subject.errors %}
                          {{ form.subject(class_="form-control is-invalid") }}
                          <div class="invalid-feedback">
                            {% for error in form.subject.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                          </div>
                      {% else %}
                          {{ form.subject(class_="form-control") }}
                      {% endif %}
                  </div>
                  <div>
                      {{ form.message.label(class_="form-label mt-3") }}
                      {% if form.message.errors %}
                          {{ form.message(class_="form-control is-invalid", rows="6") }}
                          <div class="invalid-feedback">
                            {% for error in form.message.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                          </div>
                      {% else %}
                          {{ form.message(class_="form-control", rows="6") }}
                      {% endif %}
                  </div>
                  <div>
                      {{ form.newsletter_file.label(class_="form-label mt-3") }}
                      {% if form.newsletter_file.errors %}
                          {{ form.newsletter_file(class_="form-control is-invalid") }}
                          {% if legend == "Update Newsletter" %}
                              <div class="form-text">
                                Current file is {{ newsletter_file }}
                              </div>
                          {% endif %}
                          <div class="invalid-feedback">
                            {% for error in form.newsletter_file.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                          </div>
                      {% else %}
                          {{ form.newsletter_file(class_="form-control") }}
                          {% if legend == "Update Newsletter" %}
                              <div class="form-text">
                                Current file is {{ newsletter_file }}
                              </div>
                          {% endif %}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.submit(class_="btn btn-primary mt-3") }}
                  </div>
              </form>

            </div>
          </article><!-- /.card -->

        </div>
      </div>
    </div>
{% include "footer.html" %}

blogapp/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if title %}
        <title>HE@D$P@CE - {{ title }}</title>
    {% else %}
        <title>HE@D$P@CE</title>
    {% endif %}
    <link href="{{ url_for('static', filename='css/app.css') }}" type="text/css" rel="stylesheet">
</head>
<body>

  <header>
    <nav class="navbar navbar-expand-md navbar-light bg-white absolute-top">
      <div class="container">

        <button class="navbar-toggler order-2 order-md-1" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbar-left navbar-right" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse order-3 order-md-2" id="navbar-left">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.contact') }}">Contact</a>
            </li>
          </ul>
        </div>

        <a class="navbar-brand mx-auto order-1 order-md-3" href="{{ url_for('main.home') }}">HE@D$P@CE</a>

        <div class="collapse navbar-collapse order-4 order-md-4" id="navbar-right">
          <ul class="navbar-nav ms-auto">
              {% if current_user.is_authenticated %}
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                      <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="{{ url_for('users.account') }}">Details</a>
                        <a class="dropdown-item" href="{{ url_for('users.logout') }}">logout</a>
                      </div>
                  </li>
                  {% if current_user.admin %}
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
                          <div class="dropdown-menu" aria-labelledby="dropdown02">
                            <a class="dropdown-item" href="{{ url_for('posts.new_post') }}">New Post</a>
                            <a class="dropdown-item" href="{{ url_for('users.user_list') }}">User List</a>
                            <a class="dropdown-item" href="{{ url_for('users.subscriber_list') }}">Subscriber List</a>
                            <a class="dropdown-item" href="{{ url_for('newsletters.newsletter_home') }}">Newsletters</a>
                          </div>
                      </li>
                  {% endif %}
              {% else %}
                  <li class="nav-item">
                     <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                  </li>
              {% endif %}
          </ul>
          <form method="post" action="{{ url_for('main.search') }}" class="form-inline" role="search">
            <input id="search" name="search" class="search js-search form-control form-control-rounded me-sm-2" type="text" title="Enter search query here.." placeholder="Search.." aria-label="Search">
          </form>
        </div>
      </div>
    </nav>
  </header>

  <main class="main pt-4">

blogapp/templates/post.html
{% include "header.html" %}

    <div class="container">

      <div class="row">
        <div class="col-md-9">

            {% include "flash_message.html" %}

          <article class="card mb-4">
            <header class="card-header text-center">
              <div class="card-meta">
                  <small class="fs-6">{{ post.date_posted.strftime("%d-%b-%Y") }} in <a href="{{ url_for('main.search', param=post.category) }}">{{ post.category }}</a></small>
              </div>
                <a href="{{ url_for('main.search', param=post.author.username) }}">{{ post.author.username }}</a>
                <h1 class="card-title">{{ post.title }}</h1>
            </header>
              <img class="card-img" src="{{ url_for('static', filename='post_pics/' + post.post_pic) }}" alt="" />
            <div class="card-body">

              <h4 class="fw-bold">{{ post.subtitle }}</h4>
              <p class="">{{ post.content | safe }}</p>
                {% if current_user.admin %}
                    <div class="row">
                        <div class="d-flex mt-1 justify-content-end">
                            <a class="btn btn-sm btn-primary" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                            <button
                                    class="btn btn-sm btn-danger ms-2"
                                    data-bs-toggle="modal"
                                    data-bs-target="#deleteModal">
                                Delete
                            </button>
                        </div>
                    </div>
                {% endif %}

              <hr class="mt-4" />

              <div class="mt-4">
                <h3 class="mb-3">Write a comment</h3>
                  <form action="{{ url_for('posts.show_post', post_id=post.id) }}" method="post" novalidate>
                    {{ form.csrf_token }}
                      <div>
                          {% if form.content.errors %}
                              {{ form.content(class_="form-control is-invalid", rows="6", placeholder="Comment here...") }}
                              <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                              </div>
                          {% else %}
                              {{ form.content(class_="form-control", rows="6", placeholder="Comment here...") }}
                          {% endif %}
                      </div>
                      <div>
                          {{ form.submit(class_="btn btn-success mt-3") }}
                      </div>
                  </form>
              </div>


              <h4 class="mt-4">{{ num_comments }} comments</h4>

              {% for comment in post.comments %}
                <div class="mb-4 p-4 bg-light">
                    <div class="row">
                        <div class="col-md-12 d-flex">
                            <div class="text-center">
                              <img class="me-3 rounded-circle" src="{{ url_for('static', filename='profile_pics/' + comment.comment_author.profile_pic) }}" alt="profile picture" width="100" height="100">
                              <h6 class="mt-1 mb-0 me-3">{{ comment.comment_author.username  }}</h6>
                            </div>
                            <div class="flex-grow-1">
                              <p class="mt-3 mb-2">{{ comment.content }}</p>
                              <small class="text-muted">{{ comment.date_posted.strftime("%d-%b-%Y") }} at {{ comment.date_posted.strftime("%I:%M %p") }}</small>
                              <a
                                      class="float-end"
                                      href="#reply{{ comment.date_posted.strftime("%f") }}"
                                      data-bs-toggle="collapse"
                                      role="button"
                                      aria-expanded="false"
                                      aria-controls="reply{{ comment.date_posted.strftime("%f") }}">
                                  <span class="fa fa-reply"></span>
                                  Reply
                              </a>
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-end">
                        <div class="col-md-11 col-sm-12 ">
                            <div class="collapse" id="reply{{ comment.date_posted.strftime("%f") }}">
                            <div class="card card-body border-0 mt-3">
                                <h5 class="mb-3">Reply</h5>
                                  <form action="{{ url_for('posts.new_reply', comment_id=comment.id) }}" method="post">
                                    {{ reply_form.csrf_token }}
                                      <div>
                                          {% if reply_form.content.errors %}
                                              {{ reply_form.content(class_="form-control is-invalid", rows="6", placeholder="Reply here...") }}
                                              <div class="invalid-feedback">
                                                {% for error in reply_form.content.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                              </div>
                                          {% else %}
                                              {{ reply_form.content(class_="form-control", rows="6", placeholder="Reply here...") }}
                                          {% endif %}
                                      </div>
                                      <div class="text-end">
                                          <a
                                              class="btn btn-danger mt-3"
                                              href="#reply{{ comment.date_posted.strftime("%f") }}"
                                              data-bs-toggle="collapse"
                                              role="button"
                                              aria-expanded="false"
                                              aria-controls="reply{{ comment.date_posted.strftime("%f") }}">

                                              Cancel
                                          </a>
                                          {{ reply_form.submit(class_="btn btn-success mt-3") }}
                                      </div>
                                  </form>
                            </div>
                        </div>
                        </div>
                    </div>
                    {% if comment.replies %}
                        {% for reply in comment.replies %}
                            <div class="row justify-content-end">
                                <div class="col-md-11 col-sm-12 d-flex mt-3">
                                    <div class="text-center">
                                      <img class="me-3 rounded-circle" src="{{ url_for('static', filename='profile_pics/' + reply.reply_author.profile_pic) }}" alt="profile picture" width="100" height="100">
                                      <h6 class="mt-1 mb-0 me-3">{{ reply.reply_author.username  }}</h6>
                                    </div>
                                    <div class="flex-grow-1">
                                      <p class="mt-3 mb-2">{{ reply.content }}</p>
                                      <small class="text-muted">{{ reply.date_posted.strftime("%d-%b-%Y") }} at {{ reply.date_posted.strftime("%I:%M %p") }}</small>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
              {% endfor %}

            </div>
          </article><!-- /.card -->

        </div>

          {% include "sidebar.html" %}

      </div>
    </div>

<!-- Modal for the delete button -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="post">
              <input class="btn btn-danger" type="submit" value="Delete">
          </form>
      </div>
    </div>
  </div>
</div>
<!-- Modal for the delete button -->

{% include "footer.html" %}